# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['main_category__category_name']},
        ),
    ]
